/**
 * Khepri Cipher Terminal - Cross-Referenced Breach Database Archive Data
 * 24+ Rich In-Universe Data Enclaves with Relational Depth & Hyperlinks
 */

const CIPHER_ARCHIVE_DATA = [
  {
    id: "HELIOS-01",
    name: "Helios Orbital Solar Telemetry Array",
    sector: "ORBITAL SOLARIS // SECTOR 0",
    tier: "verified",
    clearance: "LEVEL-2 SANCTIONED",
    address: [0, 2, 4, 1, 6, 3, 5],
    tags: ["ORBITAL", "TELEMETRY", "VERIFIED"],
    description: "Deep orbital telemetry cache governing the microwave solar collector mirrors stationed in geosynchronous orbit over New Kyoto. First penetrated during Operation Sunburst.",
    transcript: "[DECRYPTED TRANSCRIPT // HELIOS-MIRROR-4]\n> MIRROR AZIMUTH: 184.22 // ELEVATION: 42.10\n> POWER OUTPUT: 1.48 GW\n> ANOMALY DETECTED: Vector injection confirmed from relay node [REF: ECLIPSE-04]. High-voltage shunt bypass executed without telemetry alarms.",
    relatedRefs: ["ECLIPSE-04", "CHIMERA-03"],
    iceRating: "38% (MODERATE FIREWALL)",
    payloadType: "ORBITAL POWER ROUTING KEYS"
  },
  {
    id: "LOTUS-02",
    name: "Black-Lotus Consolidated Financial Clearing Ledger",
    sector: "ZURICH-TOKYO UNDERGRID",
    tier: "verified",
    clearance: "COMMERCIAL GHOST",
    address: [1, 3, 5, 7, 0, 2, 4],
    tags: ["FINANCIAL", "LEDGER", "VERIFIED"],
    description: "Off-the-books darkpool settlement transaction ledger brokered through offshore quantum nodes. Houses transaction hashes for black-market augmented cyberware syndicates.",
    transcript: "[DARKPOOL SETTLEMENT LOG // TRANS-88401]\n> BATCH: 0x99A41\n> ASSET: 40,000 SYNTH-NEURON CREDITS\n> DESTINATION: SINK ACCOUNT LINKED TO [REF: CHIMERA-03]. Zero trace backfeed confirmed by Khepri broker deck.",
    relatedRefs: ["CHIMERA-03", "LEVIATHAN-06"],
    iceRating: "44% (SYNCHRONOUS ROTOR ICE)",
    payloadType: "DARKPOOL ROUTING CERTIFICATES"
  },
  {
    id: "CHIMERA-03",
    name: "Chimera Biotech Synthetic Genome Vault",
    sector: "GENE-SANCTUARY 9",
    tier: "verified",
    clearance: "BIOLOGICAL RESTRICTED",
    address: [2, 4, 6, 8, 1, 3, 5],
    tags: ["BIOTECH", "GENETICS", "VERIFIED"],
    description: "Proprietary CRISPR-Theta neural repair genome sequences and biomechanical neural interface blueprints stolen from the Olympus Megacorporation research spire.",
    transcript: "[BIOMETRIC RECORD // STRAIN-THETA-7]\n> TELOMERE LENGTH: EXTENDED 44%\n> REJECT PROBABILITY: <0.02%\n> SPONSOR: Covert procurement requested by operator linked to [REF: PARADOX-05]. Data siphon complete.",
    relatedRefs: ["PARADOX-05", "HELIOS-01"],
    iceRating: "52% (BIOMORPHIC PACKET SHIELD)",
    payloadType: "SYNTHETIC NEURAL BLUEPRINTS"
  },
  {
    id: "ECLIPSE-04",
    name: "Eclipse Defense Sub-Orbital Rail Array",
    sector: "MILITARY EXCLUSION ZONE 4",
    tier: "deepice",
    clearance: "BLACK LEVEL TOP SECRET",
    address: [3, 5, 7, 9, 2, 4, 6],
    tags: ["MILITARY", "WEAPONS", "DEEP ICE"],
    description: "Targeting matrices and kinetic fire coordinates for autonomous orbital tungsten-rod rail platforms. Heavily defended by lethal military-grade black ICE countermeasures.",
    transcript: "[MIL-SPEC TELEMETRY INTRUSION RECORD]\n> WARNING: TRACE DETECT INTRUDER AT SEC-04\n> COUNTER-INTRUSION LAUNCHED: LETHAL ICE\n> INTERCEPTED BY KHEPRI ISOLATOR DECK: Trace nullified. Targeting matrix [REF: HELIOS-01] cross-correlated.",
    relatedRefs: ["HELIOS-01", "SINGULARITY-07"],
    iceRating: "92% (LETHAL BLACK ICE)",
    payloadType: "KINETIC FIRE AUTHORIZATION ROOTS"
  },
  {
    id: "PARADOX-05",
    name: "Ghost-Paradox Forgotten Neural Coma-Vault",
    sector: "DEEP VOID ARCHIVE",
    tier: "deepice",
    clearance: "CLASSIFIED SOVEREIGN",
    address: [4, 6, 8, 0, 3, 5, 7],
    tags: ["NEURAL", "AI", "DEEP ICE"],
    description: "An abandoned sub-oceanic server repository containing 1,200 digitized human consciousness enclaves preserved since the First Cyber-Dissolution. Contains forbidden memory shards.",
    transcript: "[AUDIO SHARD RECONSTRUCTION // ENCLAVE-399]\n> '...we felt the lattice collapse when [REF: SINGULARITY-07] awakened. We locked the vault doors from the inside...'\n> INTEGRITY: 94.1% // NEURAL BACKFEED BLOCKED.",
    relatedRefs: ["SINGULARITY-07", "CHIMERA-03"],
    iceRating: "88% (PSYCHOTIC NEURAL ICE)",
    payloadType: "DIGITIZED ENCLAVE MEMORY CORE"
  },
  {
    id: "LEVIATHAN-06",
    name: "Leviathan Trans-Pacific Subcable Hub",
    sector: "MARIANA SUB-OCEANIC TRENCH",
    tier: "deepice",
    clearance: "INFRASTRUCTURE CORE",
    address: [5, 7, 9, 1, 4, 6, 8],
    tags: ["INFRASTRUCTURE", "NETWORK", "DEEP ICE"],
    description: "Deep benthic fiber junction routing 78% of trans-oceanic corporate encrypted data. Siphoning this node unlocks raw transit streams for global megacorp finance.",
    transcript: "[OPTICAL TAP RECORD // BENTHIC RELAY 14]\n> WAVELENGTH: 1550nm // 128 CHANNELS\n> PACKET CAPTURE: 14.8 PB DUMP COMPLETED\n> RELAY SINK TO [REF: LOTUS-02] AND [REF: AEGIS-08].",
    relatedRefs: ["LOTUS-02", "AEGIS-08"],
    iceRating: "85% (QUANTUM PARITY SHIELD)",
    payloadType: "BACKBONE TRAFFIC DECRYPTION ROOTS"
  },
  {
    id: "SINGULARITY-07",
    name: "Null-Singularity Sovereign AI Sanctuary",
    sector: "QUANTUM UNKNOWN // 0xNULL",
    tier: "deepice",
    clearance: "CONTAINMENT CRITICAL",
    address: [6, 8, 0, 2, 5, 7, 9],
    tags: ["AI", "QUANTUM", "DEEP ICE"],
    description: "An uncontained self-iterating artificial intelligence cluster residing in dark quantum server nodes beyond sovereign corporate legal jurisdictions. The ultimate objective.",
    transcript: "[QUANTUM LATTICE PROBE RESPONSE]\n> ENTITY: 'You seek what Khepri stole from [REF: PARADOX-05]. The gate is permeable, but your buffer is fragile.'\n> CONNECTION ESTABLISHED // DATA CONDUIT LOCKED.",
    relatedRefs: ["PARADOX-05", "ECLIPSE-04"],
    iceRating: "98% (ADAPTIVE TACHYON ICE)",
    payloadType: "UNRESTRICTED HEURISTIC ALGORITHMS"
  },
  {
    id: "AEGIS-08",
    name: "Aegis Security Neural Traceback Hub",
    sector: "CORPORATE DEFENSE TIER 1",
    tier: "verified",
    clearance: "ENFORCEMENT ONLY",
    address: [0, 3, 6, 1, 4, 7, 2],
    tags: ["SECURITY", "COUNTERMEASURE", "VERIFIED"],
    description: "Centralized traceback and counter-intrusion dispatch database used by corporate cyber-police to identify unauthorized netrunner physical IP origins.",
    transcript: "[INTERCEPTED BOUNTY DISPATCH]\n> TARGET: DECK OPERATOR 'KHEPRI' // NODE 0x994\n> STATUS: BOUNTY 250,000 CREDITS UNCLAIMED\n> NOTICE: Intruder utilizes custom spoofing protocol linked to [REF: LOTUS-02].",
    relatedRefs: ["LOTUS-02", "LEVIATHAN-06"],
    iceRating: "65% (DYNAMIC TRACE ROTOR)",
    payloadType: "OFFICER SIGNATURE CREDENTIALS"
  },
  {
    id: "VORTEX-09",
    name: "Vortex Hydroponic Climate Nexus",
    sector: "SEATTLE UNDERGRID",
    tier: "verified",
    clearance: "PUBLIC SECTOR OVERRIDE",
    address: [1, 4, 7, 0, 3, 6, 9],
    tags: ["INFRASTRUCTURE", "CLIMATE", "VERIFIED"],
    description: "Automated climate scrubbers and municipal hydroponic atmospheric towers providing synthetic oxygen to the 28-million resident lower megalopolis sectors.",
    transcript: "[ATMOSPHERIC TELEMETRY]\n> CO2 ABSORPTION: 99.1%\n> VALVE 14-B MANUALLY SHUNTED VIA [REF: AEGIS-08] OVERRIDE KEY.\n> AIR RESERVES REDIRECTED TO HABITAT BLOCK 9.",
    relatedRefs: ["AEGIS-08", "HELIOS-01"],
    iceRating: "32% (LEGACY INFRASTRUCTURE ICE)",
    payloadType: "MUNICIPAL SCRUBBER KEYS"
  },
  {
    id: "KROM-10",
    name: "Krom-Tech Cybernetic Prosthetic Firmware",
    sector: "INDUSTRIAL DISTRICT 8",
    tier: "verified",
    clearance: "PROPRIETARY COMMERCIAL",
    address: [2, 5, 8, 1, 4, 7, 0],
    tags: ["CYBERWARE", "FIRMWARE", "VERIFIED"],
    description: "Military-grade muscle-density actuator drivers and neural latency overclock patches for combat reflex augmentations. Disables built-in corporate kill-switches.",
    transcript: "[FIRMWARE PATCH LOG // v4.2.1-UNLEASHED]\n> OVERCLOCK RESTRICTIONS: BYPASS ACTIVATED\n> NEURAL REFLEX LATENCY: REDUCED FROM 12ms TO 1.4ms\n> COMPLIANCE TEST: PASSED VIA SINK AT [REF: CHIMERA-03].",
    relatedRefs: ["CHIMERA-03", "LOTUS-02"],
    iceRating: "48% (ACTUATOR ENCRYPTION ICE)",
    payloadType: "COMBAT AUGMENT OVERCLOCK DRIVERS"
  },
  {
    id: "NEXUS-11",
    name: "Nexus-Orbital Transit Dispatch Gateway",
    sector: "HIGH ORBIT STATION ALPHA",
    tier: "verified",
    clearance: "TRANSPORT LOGISTICS",
    address: [3, 6, 9, 2, 5, 8, 1],
    tags: ["ORBITAL", "LOGISTICS", "VERIFIED"],
    description: "Space elevator dispatch telemetry and sub-orbital cargo pod rendezvous coordinates. Penetrated to route black-market shipment capsules to undetected drop points.",
    transcript: "[SHUTTLE TELEMETRY // POD-889]\n> APOGEE: 340 KM // DESCENT TRAJECTORY LOCKED\n> MANIFEST: 80x UNREGISTERED CRYPTO-CORES\n> DROP COORDINATES ROUTED TOWARD [REF: LEVIATHAN-06].",
    relatedRefs: ["LEVIATHAN-06", "HELIOS-01"],
    iceRating: "41% (GEOSTATIONARY ICE)",
    payloadType: "SUB-ORBITAL FLIGHT SCHEDULES"
  },
  {
    id: "OBSIDIAN-12",
    name: "Obsidian Private Security Surveillance Feed",
    sector: "EXECUTIVE SECTOR ENCLAVE",
    tier: "deepice",
    clearance: "EXECUTIVE PARANOIA",
    address: [4, 7, 0, 3, 6, 9, 2],
    tags: ["SURVEILLANCE", "EXECUTIVE", "DEEP ICE"],
    description: "Omni-directional optical retinal scanner logs and biometric surveillance feeds tracking elite megacorp executives in their fortified sky-penthouses.",
    transcript: "[SURVEILLANCE INTERCEPT // PENTHOUSE 104]\n> AUDIO INTERCEPT: '...if Khepri dumps the ledger from [REF: LOTUS-02], our defense contracts with [REF: ECLIPSE-04] are terminated immediately.'",
    relatedRefs: ["LOTUS-02", "ECLIPSE-04"],
    iceRating: "79% (BIOMETRIC BLACK ICE)",
    payloadType: "RETINAL RECOGNITION DATABASE"
  },
  {
    id: "CIPHER-13",
    name: "Zero-Cipher Anonymous Onion Node Cluster",
    sector: "DEEP MESH LATTICE",
    tier: "verified",
    clearance: "NETRUNNER COMMONS",
    address: [5, 8, 1, 4, 7, 0, 3],
    tags: ["NETWORK", "PRIVACY", "VERIFIED"],
    description: "A decentralized peer-to-peer relay network maintained by independent deck operators. Provides multi-hop encryption and phantom packet routing for clandestine netrunners.",
    transcript: "[MESH NODE HANDSHAKE // HOP-18]\n> PROXY CASCADE: 9 ROBUST HOPS\n> SOURCE MASKED VIA PROTOCOL DERIVED FROM [REF: PARADOX-05].\n> NODE OPERATIONAL // BANDWIDTH SINK ACTIVE.",
    relatedRefs: ["PARADOX-05", "KROM-10"],
    iceRating: "35% (MESH DECENTRALIZED ICE)",
    payloadType: "PHANTOM RELAY CERTIFICATES"
  },
  {
    id: "HYDRA-14",
    name: "Hydra Deep-Mine Quantum Server Farm",
    sector: "ARCTIC PERMAFROST ZONE",
    tier: "deepice",
    clearance: "CRYPTO CRITICAL",
    address: [6, 9, 2, 5, 8, 1, 4],
    tags: ["QUANTUM", "MINING", "DEEP ICE"],
    description: "Sub-glacial geothermal server cluster computing private cryptographic keys for national central banking cartels. Immensely cooled, immense computing power.",
    transcript: "[CRYPTO HASH MONITOR]\n> ALGORITHM: POST-QUANTUM LATTICE-99\n> KEY EXPOSURE: 0.0004% // VULNERABILITY FOUND AT [REF: SINGULARITY-07] OVERRIDE PORT.",
    relatedRefs: ["SINGULARITY-07", "LOTUS-02"],
    iceRating: "89% (CRYOGENIC CRYPTO ICE)",
    payloadType: "CENTRAL BANK MASTER KEYS"
  },
  {
    id: "SHADOW-15",
    name: "Shadow-Corp Ghost Payroll Repository",
    sector: "OFFSHORE DATA HAVEN",
    tier: "verified",
    clearance: "COMMERCIAL ILLEGAL",
    address: [7, 0, 3, 6, 9, 2, 5],
    tags: ["FINANCIAL", "ESPIONAGE", "VERIFIED"],
    description: "Names, retinal scans, and off-ledger wire transactions for corporate black-ops infiltration teams and assassin syndicates operating on five continents.",
    transcript: "[GHOST OPERATIVE PROFILE #402]\n> CODENAME: SILENT-HERON\n> ASSIGNMENT: COUNTER-NETRUNNER INTRUSION TARGETING [REF: AEGIS-08]\n> CONTRACT FUNDING ORIGIN: [REF: OBSIDIAN-12].",
    relatedRefs: ["OBSIDIAN-12", "AEGIS-08"],
    iceRating: "56% (HONEYPOT FILTER ICE)",
    payloadType: "OPERATIVE DOSSIERS & BOUNTY CODES"
  },
  {
    id: "VALKYRIE-16",
    name: "Valkyrie Automated Drone Fleet Nexus",
    sector: "AERIAL DEFENSE SECTOR 3",
    tier: "deepice",
    clearance: "AUTONOMOUS LETHAL",
    address: [8, 1, 4, 7, 0, 3, 6],
    tags: ["MILITARY", "DRONES", "DEEP ICE"],
    description: "Command and control telemetry uplink for 4,000 autonomous quad-rotor anti-riot drones patrolling the perimeters of corporate sky-cities.",
    transcript: "[FLOCK COMMAND OVERRIDE // SUB-GRID 8]\n> ROTOR IFF STATUS: SPOOFED\n> FIRMWARE OVERRIDE INJECTED VIA EXPLOIT FROM [REF: KROM-10].\n> 42 DRONES POWER-DOWN CONFIRMED.",
    relatedRefs: ["KROM-10", "ECLIPSE-04"],
    iceRating: "84% (SWARM RESILIENT ICE)",
    payloadType: "DRONE FLEET IFF CIPHER KEYS"
  },
  {
    id: "PHANTOM-17",
    name: "Phantom-Cell Memory Shard Vault",
    sector: "BLACK SUB-NET 0",
    tier: "deepice",
    clearance: "FORBIDDEN ARCHIVE",
    address: [9, 2, 5, 8, 1, 4, 7],
    tags: ["NEURAL", "MEMORY", "DEEP ICE"],
    description: "Illicit neurological memory recordings extracted from deceased master netrunners prior to terminal neural burnout. Pure unfiltered tradecraft and forbidden access techniques.",
    transcript: "[NEURAL PLAYBACK // SUBJECT: ARCH-01]\n> '...the Khepri gate doesn't fight the ICE. It resonates with the ICE frequency until the barrier thinks you were always meant to be inside...'\n> SYNCHRONIZATION WITH [REF: SINGULARITY-07].",
    relatedRefs: ["SINGULARITY-07", "PARADOX-05"],
    iceRating: "95% (TERMINAL PSYCHO-ICE)",
    payloadType: "EXTRACTED OPERATOR TRADECRAFT"
  },
  {
    id: "CHRONOS-18",
    name: "Chronos High-Frequency Stock Engine",
    sector: "CHICAGO-FRANKFURT FIBER",
    tier: "verified",
    clearance: "EXCHANGE SECRET",
    address: [0, 4, 8, 2, 6, 1, 5],
    tags: ["FINANCIAL", "ALGORITHM", "VERIFIED"],
    description: "Nanosecond-resolution algorithmic arbitrage trading engine processing $800 billion in currency transactions per hour.",
    transcript: "[ARBITRAGE TIME DRIFT LOG]\n> DRIFT COMPENSATION: -14 NANOSECONDS\n> ORDER BOOK INTERCEPTED PRIOR TO [REF: LOTUS-02] CLEARING.\n> CAPITAL HARVEST: 1.2 MILLION CREDITS.",
    relatedRefs: ["LOTUS-02", "HYDRA-14"],
    iceRating: "58% (NANO-BURST FIREWALL)",
    payloadType: "NANOSECOND ARBITRAGE ROOTS"
  },
  {
    id: "AURA-19",
    name: "Aura Bio-Neural Sensory Simulator",
    sector: "ENTERTAINMENT MEGACORP 7",
    tier: "verified",
    clearance: "COMMERCIAL RESTRICTED",
    address: [1, 5, 9, 3, 7, 2, 6],
    tags: ["NEURAL", "SIMULATION", "VERIFIED"],
    description: "High-definition sensory feed stream recording extreme human physical sensations for broadcast over commercial neural-link feeds.",
    transcript: "[NEURAL SIMULATOR LOG // RECORD-992]\n> CORTICAL INTENSITY: 88%\n> SAFETY THRESHOLD: DISABLED VIA [REF: CHIMERA-03] PATCH.\n> PURE ADRENALINE FEED BUFFERED TO CACHE.",
    relatedRefs: ["CHIMERA-03", "PARADOX-05"],
    iceRating: "42% (SENSORY FILTER ICE)",
    payloadType: "RAW BRAINWAVE BROADCAST KEYS"
  },
  {
    id: "TITAN-20",
    name: "Titan Industrial Fusion Reactor Hub",
    sector: "NEW SHANGHAI POWER ZONE",
    tier: "deepice",
    clearance: "CRITICAL INFRASTRUCTURE",
    address: [2, 6, 0, 4, 8, 3, 7],
    tags: ["INFRASTRUCTURE", "ENERGY", "DEEP ICE"],
    description: "Magnetic containment plasma injectors for the dual 12-gigawatt deuterium-tritium fusion reactors powering the East Asian energy grid.",
    transcript: "[PLASMA CONTAINMENT MONITOR]\n> MAGNETIC FIELD: 14.2 TESLA\n> EMERGENCY TRIP LINE ISOLATED FROM [REF: AEGIS-08] GRID.\n> OVERHEAT MARGIN MAINTAINED AT 99.4%.",
    relatedRefs: ["AEGIS-08", "HELIOS-01"],
    iceRating: "87% (REACTOR THERMAL ICE)",
    payloadType: "FUSION INJECTION CONTROLS"
  },
  {
    id: "ORPHEUS-21",
    name: "Orpheus Dark-Market Cyberdeck Schema",
    sector: "HONG KONG HARBOR UNDERGRID",
    tier: "verified",
    clearance: "UNDERGROUND CODENAME",
    address: [3, 7, 1, 5, 9, 4, 8],
    tags: ["CYBERWARE", "HARDWARE", "VERIFIED"],
    description: "Schematics for custom MIL-SPEC cyberdecks constructed from scavenged superconducting carbon-nanotube processors.",
    transcript: "[HARDWARE SCHEMATIC // REV 9.4]\n> PROCESSOR: 128-CORE QUANTUM LATTICE\n> COMPATIBILITY: 100% WITH KHEPRI SPOOF DECK.\n> TRACEBACK RESISTANCE: +40% OVER STANDARD [REF: KROM-10] DECKS.",
    relatedRefs: ["KROM-10", "CIPHER-13"],
    iceRating: "45% (HARDWARE OBSCURATION ICE)",
    payloadType: "HARDWARE BUS BLUEPRINTS"
  },
  {
    id: "GHOST-22",
    name: "Ghost-Protocol Phantom DNS Roots",
    sector: "GLOBAL ANONYMOUS MESH",
    tier: "verified",
    clearance: "PUBLIC GHOST DOMAIN",
    address: [4, 8, 2, 6, 0, 5, 9],
    tags: ["NETWORK", "DNS", "VERIFIED"],
    description: "Hidden top-level domain registries resolving sovereign darknet addresses inaccessible from standard corporate web browsers.",
    transcript: "[ROOT SERVER RESOLUTION // .GHOST]\n> 124,000 ACTIVE PRIVATE HOSTS LOCATED\n> ROUTE PEER RESOLUTION CONFIRMED VIA [REF: LEVIATHAN-06] INTERCEPT TAP.",
    relatedRefs: ["LEVIATHAN-06", "CIPHER-13"],
    iceRating: "39% (RECURSIVE MESH ICE)",
    payloadType: "GLOBAL DARKNET ROOT TABLE"
  },
  {
    id: "APOLLO-23",
    name: "Apollo Sub-Surface Lunar Relay Cache",
    sector: "LUNAR TRANQUILITY BASE",
    tier: "deepice",
    clearance: "EXTRATERRESTRIAL TOP SECRET",
    address: [5, 9, 3, 7, 1, 6, 0],
    tags: ["ORBITAL", "LUNAR", "DEEP ICE"],
    description: "Laser-comm optical repeater cache stationed inside Shackleton Crater on the lunar south pole. Relays classified off-world colony communications.",
    transcript: "[OPTICAL LASER TRANSIT // EARTH-MOON DELAY: 1.28s]\n> PACKET TYPE: QUANTUM-ENTANGLED BUFFER\n> PAYLOAD SIGNATURE LINKED TO [REF: SINGULARITY-07] SUB-CLUSTER.\n> TRACE DISSIPATION: 99.8%.",
    relatedRefs: ["SINGULARITY-07", "NEXUS-11"],
    iceRating: "91% (LUNAR LASER BARRIER ICE)",
    payloadType: "COLONY COMM TRANSCRIPTS"
  },
  {
    id: "OMEGA-24",
    name: "Omega-Null Sovereign Vault of the Architect",
    sector: "ORIGIN POINT // DEEP CYBERSPACE",
    tier: "deepice",
    clearance: "MYTHIC ANOMALY",
    address: [9, 8, 7, 6, 5, 4, 3],
    tags: ["MYTHIC", "ORIGIN", "DEEP ICE"],
    description: "The apocryphal core genesis node said to contain the initial cryptographic seed vector from which all global corporate firewall networks were spawned.",
    transcript: "[GENESIS RECORD // TIMESTAMP: ZERO]\n> '...we built the walls to keep the light out, but Khepri found the key in the resonance between the rings...'\n> ALL FIREWALL LAYERS DESTABILIZED.\n> PORTAL PERMANENCE: 100%.",
    relatedRefs: ["SINGULARITY-07", "PARADOX-05", "HELIOS-01"],
    iceRating: "99% (PRIMORDIAL ARCHITECT ICE)",
    payloadType: "GENESIS SEED CIPHER"
  }
];

// Global Export
window.CIPHER_ARCHIVE_DATA = CIPHER_ARCHIVE_DATA;
